### PR TITLE
Upgrade To Webpack 5 and React 17

### PR DESCRIPTION
**Pull request by UseTheFork**
**What does this pull request introduce? Please describe**  
Upgraded all packages to the most current or at least LTS.

The main changes are an upgrade to Webpack 5 and React 17. This also includes upgrading all corresponding packages such as react-dom etc.

This also includes the same updates as recommended by @PrimaMateria:

- I encountered 3 issues:
  -- When a webpack build entry is passed as a single string, instead of wrapping the string to array, it was split to an array of characters.
  -- Index of Nested Rules (oneOf) in Webpack module rules array changed.
  -- When env is development (start command), entry was not spliced out correctly.

- The following fixes were applied:
--Use flat() to make sure that value is an array.
--Find index of rule which contains oneOf key.
--For both Prod and Dev spice out always entry on index 0.

**How did you verify that your changes work as expected? Please describe**  

- I tested manually start and build in my local project as well as a separate project I am running locally to confirm functionality.
- Jest tests were green.
- Cypress tests are green

**Example**  
Please describe how we can try out your changes  
Run test builds on local project or via the local-test project in cypress.

**Screenshots**  
image

**Version**  
3.5.3 bumped to 4.0.0

Since this update includes a major jump and possible breaking changes for others I bumped to V4.

### CODE REVIEW

**Comment by turenc** [comment]
Supporting these versions for Direflow will add great value to the product. 
We can't use it at the moment due to version mismatch.

Will this pr be Merge?

**Comment by use-the-fork** [comment]
> Supporting these versions for Direflow will add great value to the product. We can't use it at the moment due to version mismatch.
> 
> Will this pr be Merge?

I am not sure but if you would like to use it now I created 2 forks in NPM that you can use the same way as direflow now:
https://www.npmjs.com/package/@use-the-fork/direflow-cli
https://www.npmjs.com/package/@use-the-fork/direflow-component
https://www.npmjs.com/package/@use-the-fork/direflow-scripts

I have been using the upgrade for a few days now and am very happy with it.

**Comment by PrimaMateria** [comment]
We should figure out something. I have also my own fork with some updates and also recently I added a plugin that supports Material UI 5. Maybe we could form a group of volunteers and if @SimonHoiberg would agree, he could grant as a maintainers' permission on this repo.

If, for whatever reason, the owner is unavailable, then we could still create our own fork. But it would be a pity to lose all the stars that this repo has already received.

**Comment by JohnDeved** [comment]
I've reached out to Simon about it. I'm sure he would happily accept some volunteer maintainers. He wanted to archive the repo since there hasn't been any active development on it for a while because all maintainers moved away from it.

**Comment by SimonHoiberg** [comment]
Thanks for adding to this project.
I would be very happy to add you as maintainers.

Please reply below so I know who of you would like to participate, @use-the-fork, @turenc, @PrimaMateria.

**Comment by PrimaMateria** [comment]
Please add me

**Comment by use-the-fork** [comment]
> Thanks for adding to this project. I would be very happy to add you as maintainers.
> 
> Please reply below so I know who of you would like to participate, @use-the-fork, @turenc, @PrimaMateria.

Yes please add me! I have found this project very useful!

**Comment by turenc** [comment]
> Thanks for adding to this project. I would be very happy to add you as maintainers.
> 
> Please reply below so I know who of you would like to participate, @use-the-fork, @turenc, @PrimaMateria.

Hi Simon, I want to join and contribute to the community. Thanks.

**Comment by SimonHoiberg** [comment]
Hey, @use-the-fork, @PrimaMateria, and @turenc.

I have invited you to become collaborators on the project.

**Comment by PrimaMateria** [comment]
Thanks @SimonHoiberg for invite

@use-the-fork I had first look around your PR and I hit an issue when running `npm run test`, because `Test environment jest-environment-jsdom-fourteen cannot be found`. I also run CI to verify that it's not some issue on my local.

If you don't mind, I am planning to spend more time reviewing your PR, but after I come back from vacation in one week.

**Comment by turenc** [comment]
Thanks for invite @SimonHoiberg

**Review by giacesaro — APPROVED** [review]

**Comment by olofsellgren** [comment]
Hi!
@use-the-fork, @turenc and @PrimaMateria
I'm just wondering if you are planning on merging this PR and maybe maintain the project for a while?
It would be really great if that is the case. The project I'm involved with now would benefit greatly from it.

**Comment by PrimaMateria** [comment]
I now have a bit higher load and pressure on the job's project. I hope once the project will finish, I will have again more time for the maintenance. I didn't forget about the Direflow, and it is still on my to-do list to finalize this PR.

**Comment by irhamputra** [comment]
any update on this issue?

**Review by turenc — APPROVED** [review]

**Comment by PrimaMateria** [comment]
I have fixed all the tests. But I am not authorized to merge. @SimonHoiberg will you do it?

Also while fixing, I have reverted MUI plugin back to v4. It will be good to not override it, I would rather in separate PR add new plugin for MUI v5.

**Comment by bwassermann** [comment]
@SimonHoiberg any update on this issue? can u merge this pull request?

**Comment by JohnDeved** [comment]
@PrimaMateria merged

**Pull request merged**
